### ISSUE TITLE
Creating TreeAutomata from ta.toString() representations

### ISSUE THREAD

**Issue by akoehn** [coli-saar/alto#72]
I am currently trying to read in a condensed TA I obtained from a toString method.  `CondensedTreeAutomatonParser.parse(new StringReader(taStr))` seems to be the way to go but I noticed that the `CondensedTreeAutomatonParser.jj` grammar wants to have labels in every rule.

1. what are these labels?
2. is my idea to read a TA back from string using that parser correct?
3. If so, should the string representation be changed to have labels (whatever they are) or the parser to accept TAs without labels?

**Comment by akoehn** [comment]
From my understanding, the toString methods encodes the same information but in a slightly different way.  Is there a general use-case for reading tree automata back in from a string representation?  If not, then I'll just try to hack my way around the problem for my debugging purposes.

**Comment by alexanderkoller** [comment]
As far as I can tell, `CondensedTreeAutomaton#parse` is inherited from `TreeAutomaton`. This is quite obviously not correct. Each rule of a CTA can have a whole set of labels (that's what "condensed" means, see [here](http://www.coli.uni-saarland.de/~koller/showpaper.php?id=irtg-parsing-16) in Section 5), and TreeAutomaton#parse assumes there is only one label per rule.

The correct way to deal with this is to implement an input and output codec for CTAs; in fact, all "parse" methods in Alto should only be shorthand for calls to the parse method of a standard input codec. I don't know why we never implemented these codecs - it is probably because we only ever saw CTAs as intermediate data structures that arise in the middle of the parsing algorithm, and not as something that is worth saving and loading. It would probably not be hard to extend TreeAutomatonInputCodec into CondensedTreeAutomatonInputCodec - all you'd have to do is to expect sets of labels in each rule and then call `CondensedTreeAutomaton#createRule` instead of `TreeAutomaton#createRule`.

Can you explain why you need to save and load CTAs?

**Comment by alexanderkoller** [comment]
> Is there a general use-case for reading tree automata back in from a string representation? 

For standard tree automata, the TreeAutomatonInputCodec will do this. This is covered by unit tests.

**Comment by akoehn** [comment]
Ah, that works. I don't know why I missed it; maybe because the rules look different in the javadoc due to the `-&gt;` instead of `->`.
